[package]
name = "simple-example"
version = "0.0.0"
edition = "2021"

[dependencies]
# tonic
tonic = "0.8"
prost = "0.11"
actix-web = "4.2"
actix-web-tonic = { path = "../../" }
# for this example
num_cpus = "1.13.1"
log = "0.4.17"
simple_logger = "2.3.0"

[build-dependencies]
tonic-build = "0.8"
